[package]
name = "src"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
solana-program = "2.1.11" # Adjust the version as necessary
borsh = "1.5.5" # Adjust the version as necessary
